"""Add active field to User model

Revision ID: 38491180a8cb
Revises: 33f89433d79e
Create Date: 2025-06-18 11:44:05.112665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38491180a8cb'
down_revision = '33f89433d79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
